name: Checkout PyTorch

description: Clean workspace and check out PyTorch

inputs:
  no-sudo:
    description: If set to any value, don't use sudo to clean the workspace
    required: false
  submodules:
    description: Works as stated in actions/checkout, but the default value is recursive
    required: false
    default: recursive
  other-refs:
    description: Additonal refs to fetch
    default: refs/heads/viable/strict refs/heads/master
    required: false

runs:
  using: composite
  steps:
    - name: Clean workspace
      shell: bash
      env:
        NO_SUDO: ${{ inputs.no-sudo }}
      run: |
        echo "${GITHUB_WORKSPACE}"
        if [ -z "${NO_SUDO}" ]; then
          sudo rm -rf "${GITHUB_WORKSPACE}"
        else
          rm -rf "${GITHUB_WORKSPACE}"
        fi
        mkdir "${GITHUB_WORKSPACE}"

    - name: echo
      shell: bash
      env:
        THING: ${{ toJSON(github.event) }}
      run: echo "hello"
    - name: Checkout PyTorch
      uses: clee2000/checkout@fetch-depth
      with:
        other-refs: ${{ inputs.other-refs }}
        ref: ${{ (github.event_name == 'pull_request' && github.event.pull_request.head.sha) || github.sha }}
        # deep clone, to allow use of git merge-base
        fetch-depth: -1
        submodules: ${{ inputs.submodules }}
